import { MigrationInterface, QueryRunner } from 'typeorm';

export class Init1591515407866 implements MigrationInterface {
  name = 'Init1591515407866';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TYPE "accessory_layout_type_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TABLE "accessory_layout" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" "accessory_layout_type_enum" NOT NULL, "comment" character varying NOT NULL, "proposalId" uuid, CONSTRAINT "PK_89f8b8e5209eaceecd13798c2ea" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "procedure_step" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "comment" character varying NOT NULL, "procedureId" uuid, CONSTRAINT "PK_a726f15085827688a805d874a68" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "project_procedure_type_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TABLE "project_procedure" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" "project_procedure_type_enum" NOT NULL, "proposalId" uuid, CONSTRAINT "PK_b455eb8f1c98b451b33fda7a32f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "cost_estimate_type_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TABLE "cost_estimate" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" "cost_estimate_type_enum" NOT NULL, "comment" character varying NOT NULL, "accept" boolean NOT NULL DEFAULT true, "cost" numeric(17,2) NOT NULL DEFAULT 0, "proposalId" uuid, CONSTRAINT "PK_deb00413cf240ce4233861d8c25" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "final_proposal_status_enum" AS ENUM('ACCEPTED', 'DECLINED', 'PENDING')`, undefined);
    await queryRunner.query(`CREATE TYPE "final_proposal_declinereasons_enum" AS ENUM('BUDGET_MISMATCH', 'NOT_READY', 'CHOSEN_ANOTHER_CONTRACTOR')`, undefined);
    await queryRunner.query(`CREATE TABLE "final_proposal" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "existingSiteAssessment" character varying NOT NULL, "paversSize" character varying NOT NULL, "paversColor" character varying NOT NULL, "paversQuality" character varying NOT NULL, "existingMaterialRemoval" character varying NOT NULL, "startDate" TIMESTAMP NOT NULL, "endDate" TIMESTAMP NOT NULL, "workPlan" character varying NOT NULL, "status" "final_proposal_status_enum" NOT NULL DEFAULT 'PENDING', "declineReasons" "final_proposal_declinereasons_enum" array NOT NULL DEFAULT '{}', "declineComment" character varying DEFAULT '', "discount" numeric(17,2) NOT NULL DEFAULT 0, CONSTRAINT "PK_0de093ab48935f233a5bfe6a3bd" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_item_type_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_item_materials_enum" AS ENUM('PAVERS', 'NATURAL_STONE', 'BLUE_STONE', 'GRANITE', 'BRICK', 'SRW_SYSTEMS', 'SLATE', 'FIELD_STONE', 'BOULDERS', 'CONCRETE', 'STAMPED_CONCRETE', 'SYNTHETIC_GRASS', 'MANUFACTURED_BLOCK', 'VENEER', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_item_locationtype_enum" AS ENUM('FRONT_YARD', 'BACK_YARD', 'SIDE_YARD', 'PART_OF_PATIO_DESIGN', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_item_costunit_enum" AS ENUM('SQUARE_FOOT', 'LINER_FOOT', 'TOTAL', 'TOTAL_PLUS_TAX', 'STEP', 'PILLAR', 'UNIT')`, undefined);
    await queryRunner.query(`CREATE TABLE "estimate_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" "estimate_item_type_enum" NOT NULL, "materials" "estimate_item_materials_enum" array NOT NULL DEFAULT '{}', "locationType" "estimate_item_locationtype_enum" NOT NULL, "size" character varying NOT NULL, "comment" character varying NOT NULL, "costUnit" "estimate_item_costunit_enum" NOT NULL, "pricePerUnit" numeric(17,2) NOT NULL, "estimateId" uuid, CONSTRAINT "PK_5fef8c6ee2b65633efff895181f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "site_visit_schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "from" TIMESTAMP NOT NULL, "to" TIMESTAMP NOT NULL, "selected" boolean NOT NULL DEFAULT false, "reminderSent" boolean NOT NULL DEFAULT false, "estimateId" uuid, CONSTRAINT "PK_f30885a8f31074c011ad590a6b1" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_projecttype_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_materials_enum" AS ENUM('PAVERS', 'NATURAL_STONE', 'BLUE_STONE', 'GRANITE', 'BRICK', 'SRW_SYSTEMS', 'SLATE', 'FIELD_STONE', 'BOULDERS', 'CONCRETE', 'STAMPED_CONCRETE', 'SYNTHETIC_GRASS', 'MANUFACTURED_BLOCK', 'VENEER', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_locationtype_enum" AS ENUM('FRONT_YARD', 'BACK_YARD', 'SIDE_YARD', 'PART_OF_PATIO_DESIGN', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_shapetype_enum" AS ENUM('STRAIGHT', 'CURVED_CORNERS', 'S_SHAPED', 'FREE_FORM', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_costunit_enum" AS ENUM('SQUARE_FOOT', 'LINER_FOOT', 'TOTAL', 'TOTAL_PLUS_TAX', 'STEP', 'PILLAR', 'UNIT')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_timelinetype_enum" AS ENUM('IMMEDIATELY', 'ABOUT_30_DAYS', 'ABOUT_1_TO_3_MONTHS', 'ABOUT_3_TO_MONTHS', 'MORE_THEN_6_MONTHS')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_status_enum" AS ENUM('DECLINED', 'PENDING', 'SITE_VISIT_SCHEDULED')`, undefined);
    await queryRunner.query(`CREATE TYPE "estimate_declinereasons_enum" AS ENUM('BUDGET_MISMATCH', 'NOT_READY', 'CHOSEN_ANOTHER_CONTRACTOR')`, undefined);
    await queryRunner.query(`CREATE TABLE "estimate" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "projectType" "estimate_projecttype_enum" NOT NULL, "materials" "estimate_materials_enum" array NOT NULL DEFAULT '{}', "locationType" "estimate_locationtype_enum" NOT NULL, "groundState" character varying NOT NULL DEFAULT '', "projectSize" character varying NOT NULL DEFAULT '', "shapeType" "estimate_shapetype_enum", "requestDetails" character varying NOT NULL DEFAULT '', "coreProjectComment" character varying NOT NULL DEFAULT '', "costUnit" "estimate_costunit_enum" NOT NULL, "pricePerUnit" numeric(17,2) NOT NULL, "timelineType" "estimate_timelinetype_enum" NOT NULL, "comment" character varying NOT NULL, "status" "estimate_status_enum" NOT NULL DEFAULT 'PENDING', "declineReasons" "estimate_declinereasons_enum" array NOT NULL DEFAULT '{}', "declineComment" character varying DEFAULT '', CONSTRAINT "PK_75c20205845608fdb6725d7b130" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "image_attachment" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "url" character varying NOT NULL, "projectId" uuid, "proposalId" uuid, "estimateId" uuid, "accessoryLayoutId" uuid, CONSTRAINT "PK_0824f9490ec1196fe97eef26a13" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "project_accessory_materials_enum" AS ENUM('PAVERS', 'NATURAL_STONE', 'BLUE_STONE', 'GRANITE', 'BRICK', 'SRW_SYSTEMS', 'SLATE', 'FIELD_STONE', 'BOULDERS', 'CONCRETE', 'STAMPED_CONCRETE', 'SYNTHETIC_GRASS', 'MANUFACTURED_BLOCK', 'VENEER', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_accessory_locationtype_enum" AS ENUM('FRONT_YARD', 'BACK_YARD', 'SIDE_YARD', 'PART_OF_PATIO_DESIGN', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_accessory_shape_enum" AS ENUM('STRAIGHT', 'CURVED_CORNERS', 'S_SHAPED', 'FREE_FORM', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TABLE "project_accessory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "materials" "project_accessory_materials_enum" array NOT NULL DEFAULT '{}', "locationType" "project_accessory_locationtype_enum", "size" character varying NOT NULL DEFAULT '', "shape" "project_accessory_shape_enum", "groundState" character varying NOT NULL DEFAULT '', "comment" character varying NOT NULL DEFAULT '', "projectId" uuid, CONSTRAINT "PK_24baa2831b5a0abb33bf3e92bef" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "milestone_status_enum" AS ENUM('PENDING', 'RELEASE_REQUESTED', 'RELEASED')`, undefined);
    await queryRunner.query(`CREATE TABLE "milestone" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "order" integer NOT NULL, "amount" numeric(17,2) NOT NULL, "comment" character varying NOT NULL, "paidDate" TIMESTAMP, "paymentId" character varying, "payWithCash" boolean DEFAULT false, "status" "milestone_status_enum" NOT NULL DEFAULT 'PENDING', "projectId" uuid, CONSTRAINT "PK_f8372abce331f60ba7b33fe23a7" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "idea_projecttype_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "idea_materialtypes_enum" AS ENUM('PAVERS', 'NATURAL_STONE', 'BLUE_STONE', 'GRANITE', 'BRICK', 'SRW_SYSTEMS', 'SLATE', 'FIELD_STONE', 'BOULDERS', 'CONCRETE', 'STAMPED_CONCRETE', 'SYNTHETIC_GRASS', 'MANUFACTURED_BLOCK', 'VENEER', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TABLE "idea" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "indexNumber" integer NOT NULL, "url" character varying NOT NULL, "width" integer, "height" integer, "projectType" "idea_projecttype_enum" NOT NULL, "materialTypes" "idea_materialtypes_enum" array NOT NULL, CONSTRAINT "PK_5096f543c484b349f5234da9d97" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "patio_package_packagetype_enum" AS ENUM('ECONOMY_SERIES', 'ENTERTAINMENT_SERIES', 'EXECUTIVE_SERIES', 'DECK_EXTENDER_SERIES', 'WALKWAY_PACKAGES', 'NEW_POOL_PATIO_PACKAGES', 'HARDSCAPE_BAR', 'HARDSCAPE_COUCH', 'HARDSCAPE_GRILL')`, undefined);
    await queryRunner.query(`CREATE TYPE "patio_package_additional_enum" AS ENUM('FIRE_PIT', 'SITTING_WALL', 'PILLARS', 'WALL_LIGHTS', 'OUTDOOR_SPEAKERS', 'TIMBER_FRAME_OR_VINYL_PAVILION', 'OUTDOOR_LIGHTING', 'LANDSCAPE_DESIGN_AND_INSTALLATION', 'GRANITE_STEPS', 'SIDE_RETAINING_WALLS', 'CURBING', 'POOL_COPING')`, undefined);
    await queryRunner.query(`CREATE TABLE "patio_package" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "packageType" "patio_package_packagetype_enum" NOT NULL, "additional" "patio_package_additional_enum" array NOT NULL DEFAULT '{}', "option" character varying, CONSTRAINT "PK_d72cff707181cb1d64ce4dda4d6" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "consultation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "datetime" TIMESTAMP NOT NULL, "userId" uuid, "patioPackageId" uuid, CONSTRAINT "REL_bb8961abd76c46fcbd7644f696" UNIQUE ("patioPackageId"), CONSTRAINT "PK_5203569fac28a4a626c42abe70b" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "message" character varying NOT NULL, "readAt" character varying DEFAULT null, "image" character varying DEFAULT null, "meta" json DEFAULT null, "userId" uuid, CONSTRAINT "PK_30c2f3bbaf6d34a55f8ae6e4614" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "contractor_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0e915805d46137cd1b351024c8c" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "customer_visit_history_page_enum" AS ENUM('BRIEF_PAGE', 'ESTIMATE_PAGE', 'PROPOSAL_PAGE', 'CONTRACT_PAGE', 'PAYMENT_PAGE')`, undefined);
    await queryRunner.query(`CREATE TABLE "customer_visit_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "page" "customer_visit_history_page_enum" NOT NULL, "visitDate" TIMESTAMP NOT NULL, "customerId" uuid, "projectId" uuid, CONSTRAINT "PK_162539525cdc3b4674996ff04c5" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "user_role_enum" AS ENUM('SUPER_ADMIN', 'CONTRACTOR', 'CUSTOMER')`, undefined);
    await queryRunner.query(`CREATE TYPE "user_invitationstatus_enum" AS ENUM('PENDING', 'SENT', 'ACCEPTED')`, undefined);
    await queryRunner.query(`CREATE TABLE "user" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone" character varying NOT NULL, "isEmailVerified" boolean NOT NULL DEFAULT false, "role" "user_role_enum" NOT NULL, "password" character varying NOT NULL, "avatar" character varying DEFAULT null, "address" character varying DEFAULT '', "latitude" numeric(20,15), "longitude" numeric(20,15), "stripeCustomerId" character varying DEFAULT null, "invitationStatus" "user_invitationstatus_enum" NOT NULL DEFAULT 'PENDING', "customerProfileId" uuid, "contractorProfileId" uuid, CONSTRAINT "REL_b856cc54559328413b5652ab98" UNIQUE ("customerProfileId"), CONSTRAINT "REL_e72528f4484a73df51e7578d54" UNIQUE ("contractorProfileId"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "customer_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d3e8a37b75a6e92258188f59403" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "payment_add_on" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "amount" numeric(17,2) NOT NULL, "payDate" TIMESTAMP, "comment" character varying NOT NULL, "projectId" uuid, CONSTRAINT "PK_4f85c656fb07aaea4f2adca89a0" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "refund" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "amount" numeric(17,2) NOT NULL, "refundDate" TIMESTAMP, "comment" character varying NOT NULL, CONSTRAINT "PK_f1cefa2e60d99b206c46c1116e5" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "project_projecttype_enum" AS ENUM('STEPS', 'SITTING_WALL', 'PILLARS', 'LIGHTING', 'PATIO', 'RAISED_PATIO', 'WALKWAY', 'RETAINING_WALL', 'POOL_PATIO', 'FIRE_PIT', 'DRIVEWAY_PARKING', 'VENEER', 'FIREPLACE', 'OUTDOOR_KITCHEN', 'CLEANING_SANDING', 'MINOR_REPAIR', 'LANDSCAPING_PLANTS', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_locationtype_enum" AS ENUM('FRONT_YARD', 'BACK_YARD', 'SIDE_YARD', 'PART_OF_PATIO_DESIGN', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_shapetype_enum" AS ENUM('STRAIGHT', 'CURVED_CORNERS', 'S_SHAPED', 'FREE_FORM', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_timelinetype_enum" AS ENUM('IMMEDIATELY', 'ABOUT_30_DAYS', 'ABOUT_1_TO_3_MONTHS', 'ABOUT_3_TO_MONTHS', 'MORE_THEN_6_MONTHS')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_interestedinfinancing_enum" AS ENUM('YES', 'NO', 'NOT_SURE')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_cleanuptype_enum" AS ENUM('TOPSOIL', 'NO_TOPSOIL', 'TOPSOIL_AND_SEED', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_materials_enum" AS ENUM('PAVERS', 'NATURAL_STONE', 'BLUE_STONE', 'GRANITE', 'BRICK', 'SRW_SYSTEMS', 'SLATE', 'FIELD_STONE', 'BOULDERS', 'CONCRETE', 'STAMPED_CONCRETE', 'SYNTHETIC_GRASS', 'MANUFACTURED_BLOCK', 'VENEER', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_preferredpricepoint_enum" AS ENUM('ECONOMY', 'AVERAGE', 'ABOVE_AVERAGE')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_preferredcolors_enum" AS ENUM('EARTH_TONE', 'BROWN', 'SHALE_GREY', 'CHAMPLAIN_GREY', 'ONYX_BLACK', 'DANVILLE_BLEND', 'SHERWOOD', 'CHESTNUT_BROWN', 'SANDLEWOOD', 'HICKORY', 'BEDFORD_BROWN')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_machineaccess_enum" AS ENUM('YES', 'NO', 'NOT_SURE')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_propertygrade_enum" AS ENUM('LEVEL', 'FAIRLY_LEVEL', 'WELL_OUT_OF_LEVEL')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_soiltype_enum" AS ENUM('CLAY', 'SAND', 'ROCK', 'TOP_SOIL')`, undefined);
    await queryRunner.query(`CREATE TYPE "project_drainagetype_enum" AS ENUM('DRY', 'SOFT_IN_SPRING', 'WET_YEAR_ROUND')`, undefined);
    await queryRunner.query(`CREATE TABLE "project" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "address" character varying NOT NULL, "latitude" numeric(20,15), "longitude" numeric(20,15), "projectType" "project_projecttype_enum" NOT NULL, "locationType" "project_locationtype_enum" NOT NULL, "projectSize" character varying NOT NULL DEFAULT '', "shapeType" "project_shapetype_enum", "timelineType" "project_timelinetype_enum" NOT NULL, "interestedInFinancing" "project_interestedinfinancing_enum" NOT NULL DEFAULT 'NOT_SURE', "designRequired" boolean NOT NULL DEFAULT false, "cleanUpType" "project_cleanuptype_enum", "materials" "project_materials_enum" array NOT NULL DEFAULT '{}', "requestDetails" character varying NOT NULL DEFAULT '', "budget" integer NOT NULL, "manufacturer" character varying NOT NULL DEFAULT '', "productName" character varying NOT NULL DEFAULT '', "preferredSize" character varying NOT NULL DEFAULT '', "preferredTexture" character varying NOT NULL DEFAULT '', "preferredPricePoint" "project_preferredpricepoint_enum" NOT NULL DEFAULT 'ECONOMY', "preferredColors" "project_preferredcolors_enum" array NOT NULL DEFAULT '{}', "additionalDesigns" character varying NOT NULL DEFAULT '', "machineAccess" "project_machineaccess_enum" NOT NULL, "propertyGrade" "project_propertygrade_enum" NOT NULL, "soilType" "project_soiltype_enum" NOT NULL, "drainageType" "project_drainagetype_enum" NOT NULL, "exteriorUtilities" character varying NOT NULL DEFAULT '', "exteriorHazards" character varying NOT NULL DEFAULT '', "exteriorInconveniences" character varying NOT NULL DEFAULT '', "materialStorage" character varying NOT NULL DEFAULT '', "materialHaulOut" character varying NOT NULL DEFAULT '', "downSpouts" character varying NOT NULL DEFAULT '', "shrubRemoval" character varying NOT NULL DEFAULT '', "comment" character varying NOT NULL DEFAULT '', "contractSignedDate" TIMESTAMP, "estimateSkipped" boolean NOT NULL DEFAULT false, "estimateReminderSent" boolean NOT NULL DEFAULT false, "customerId" uuid, "contractorId" uuid, "estimateId" uuid, "finalProposalId" uuid, "chatId" uuid, "refundId" uuid, CONSTRAINT "REL_aad9c3fcb70b081eac170c9f85" UNIQUE ("estimateId"), CONSTRAINT "REL_0a0437d89bd29852d51db89b58" UNIQUE ("finalProposalId"), CONSTRAINT "REL_730de7831f17b647a4a0d5602f" UNIQUE ("chatId"), CONSTRAINT "REL_64f56c961989b6c00408dd6e5c" UNIQUE ("refundId"), CONSTRAINT "PK_4d68b1358bb5b766d3e78f32f57" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "message_from_enum" AS ENUM('FROM_CONTRACTOR', 'FROM_CUSTOMER')`, undefined);
    await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "text" character varying NOT NULL, "from" "message_from_enum" NOT NULL, "attachments" text DEFAULT null, "readAt" character varying DEFAULT null, "mailed" boolean NOT NULL DEFAULT false, "chatId" uuid, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "chat" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9d0b2ba74336710fd31154738a5" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "contact_us_message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "email" character varying NOT NULL, "phone" character varying NOT NULL, "fullName" character varying NOT NULL, "message" character varying NOT NULL, CONSTRAINT "PK_ec8d45dfb566246228195e04ef0" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "job_type_enum" AS ENUM('PART_TIME', 'FULL_TIME')`, undefined);
    await queryRunner.query(`CREATE TYPE "job_salarytype_enum" AS ENUM('YEAR', 'MONTH', 'HOUR')`, undefined);
    await queryRunner.query(`CREATE TABLE "job" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "title" character varying NOT NULL, "description" character varying NOT NULL, "type" "job_type_enum" NOT NULL, "salary" numeric NOT NULL, "salaryType" "job_salarytype_enum" NOT NULL, "remote" boolean NOT NULL, "hardSkills" text DEFAULT null, "softSkills" text DEFAULT null, CONSTRAINT "PK_98ab1c14ff8d1cf80d18703b92f" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "applicant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "fullName" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying NOT NULL, "cv" character varying DEFAULT null, "jobId" uuid, CONSTRAINT "PK_f4a6e907b8b17f293eb073fc5ea" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "network_contractor" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "companyName" character varying NOT NULL, "address" character varying NOT NULL, "contacts" character varying NOT NULL, "website" character varying NOT NULL, "serviceDescription" character varying NOT NULL, "logoUrl" character varying NOT NULL, "categoryId" uuid, CONSTRAINT "PK_cc189ad1fecb9e2c7c4e9769912" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "network_contractor_category" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL, "published" boolean NOT NULL, CONSTRAINT "PK_b5b819a747b262666199f2f0f5d" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TYPE "portfolio_materials_enum" AS ENUM('PAVERS', 'NATURAL_STONE', 'BLUE_STONE', 'GRANITE', 'BRICK', 'SRW_SYSTEMS', 'SLATE', 'FIELD_STONE', 'BOULDERS', 'CONCRETE', 'STAMPED_CONCRETE', 'SYNTHETIC_GRASS', 'MANUFACTURED_BLOCK', 'VENEER', 'OTHER')`, undefined);
    await queryRunner.query(`CREATE TABLE "portfolio" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "deletedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "name" character varying NOT NULL DEFAULT '', "materials" "portfolio_materials_enum" array NOT NULL, "address" character varying NOT NULL DEFAULT '', "email" character varying NOT NULL DEFAULT '', "phone" character varying NOT NULL DEFAULT '', "comment" character varying NOT NULL DEFAULT '', CONSTRAINT "PK_6936bb92ca4b7cda0ff28794e48" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "password_reset_link" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "expireDate" TIMESTAMP NOT NULL, CONSTRAINT "PK_2433643537b59c8de4d86d4e428" PRIMARY KEY ("id"))`, undefined);
    await queryRunner.query(`CREATE TABLE "user_ideas_idea" ("userId" uuid NOT NULL, "ideaId" uuid NOT NULL, CONSTRAINT "PK_62c9e9a2ca06bb7d41322be92be" PRIMARY KEY ("userId", "ideaId"))`, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_88acbdbb95efe26f6a5fde1e96" ON "user_ideas_idea" ("userId") `, undefined);
    await queryRunner.query(`CREATE INDEX "IDX_43a25f9db30db5c7bca3352738" ON "user_ideas_idea" ("ideaId") `, undefined);
    await queryRunner.query(`ALTER TABLE "accessory_layout" ADD CONSTRAINT "FK_a94e33cc1557b3e696264b972a1" FOREIGN KEY ("proposalId") REFERENCES "final_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "procedure_step" ADD CONSTRAINT "FK_35021ebabf1ce8152e4f2d3a986" FOREIGN KEY ("procedureId") REFERENCES "project_procedure"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project_procedure" ADD CONSTRAINT "FK_801d68af50498ef865562a2ea0a" FOREIGN KEY ("proposalId") REFERENCES "final_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "cost_estimate" ADD CONSTRAINT "FK_2239571281051540baf9b07e7e3" FOREIGN KEY ("proposalId") REFERENCES "final_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "estimate_item" ADD CONSTRAINT "FK_6d9aa5f11e0d5805802567d129a" FOREIGN KEY ("estimateId") REFERENCES "estimate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "site_visit_schedule" ADD CONSTRAINT "FK_10b08c17f53e1a2a7d8403e48b6" FOREIGN KEY ("estimateId") REFERENCES "estimate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" ADD CONSTRAINT "FK_79944b399d8cd03eb680c62b786" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" ADD CONSTRAINT "FK_ae5a68622fea0de6fdff500719e" FOREIGN KEY ("proposalId") REFERENCES "final_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" ADD CONSTRAINT "FK_1be8a3da9176bbd92660905c9de" FOREIGN KEY ("estimateId") REFERENCES "estimate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" ADD CONSTRAINT "FK_2c5dad24fda3550532497952ebc" FOREIGN KEY ("accessoryLayoutId") REFERENCES "accessory_layout"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project_accessory" ADD CONSTRAINT "FK_e72d6667e0a330dfba21e0452f3" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "milestone" ADD CONSTRAINT "FK_edc28a2e0442554afe5eef2bdcb" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_5fdef95bb1290b8daff57fa3b4b" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "consultation" ADD CONSTRAINT "FK_bb8961abd76c46fcbd7644f6966" FOREIGN KEY ("patioPackageId") REFERENCES "patio_package"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_01cd2b829e0263917bf570cb672" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "customer_visit_history" ADD CONSTRAINT "FK_796a73e0119fa583f4fb6fb75c3" FOREIGN KEY ("customerId") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "customer_visit_history" ADD CONSTRAINT "FK_a63722084fb1d381526e4b66319" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_b856cc54559328413b5652ab980" FOREIGN KEY ("customerProfileId") REFERENCES "customer_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_e72528f4484a73df51e7578d54f" FOREIGN KEY ("contractorProfileId") REFERENCES "contractor_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "payment_add_on" ADD CONSTRAINT "FK_cce8bed0f7eb60daae3c2031067" FOREIGN KEY ("projectId") REFERENCES "project"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_b76640329fa79f0b0e9d031c35b" FOREIGN KEY ("customerId") REFERENCES "customer_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_bd374c8eb325f260166479c2518" FOREIGN KEY ("contractorId") REFERENCES "contractor_profile"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_aad9c3fcb70b081eac170c9f855" FOREIGN KEY ("estimateId") REFERENCES "estimate"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_0a0437d89bd29852d51db89b589" FOREIGN KEY ("finalProposalId") REFERENCES "final_proposal"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_730de7831f17b647a4a0d5602ff" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "project" ADD CONSTRAINT "FK_64f56c961989b6c00408dd6e5cf" FOREIGN KEY ("refundId") REFERENCES "refund"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_619bc7b78eba833d2044153bacc" FOREIGN KEY ("chatId") REFERENCES "chat"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "applicant" ADD CONSTRAINT "FK_98da5dfa6c0a087f974800b93ac" FOREIGN KEY ("jobId") REFERENCES "job"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "network_contractor" ADD CONSTRAINT "FK_14f81634276f827e9b98b806d8a" FOREIGN KEY ("categoryId") REFERENCES "network_contractor_category"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "user_ideas_idea" ADD CONSTRAINT "FK_88acbdbb95efe26f6a5fde1e967" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
    await queryRunner.query(`ALTER TABLE "user_ideas_idea" ADD CONSTRAINT "FK_43a25f9db30db5c7bca3352738f" FOREIGN KEY ("ideaId") REFERENCES "idea"("id") ON DELETE CASCADE ON UPDATE NO ACTION`, undefined);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE "user_ideas_idea" DROP CONSTRAINT "FK_43a25f9db30db5c7bca3352738f"`, undefined);
    await queryRunner.query(`ALTER TABLE "user_ideas_idea" DROP CONSTRAINT "FK_88acbdbb95efe26f6a5fde1e967"`, undefined);
    await queryRunner.query(`ALTER TABLE "network_contractor" DROP CONSTRAINT "FK_14f81634276f827e9b98b806d8a"`, undefined);
    await queryRunner.query(`ALTER TABLE "applicant" DROP CONSTRAINT "FK_98da5dfa6c0a087f974800b93ac"`, undefined);
    await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_619bc7b78eba833d2044153bacc"`, undefined);
    await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_64f56c961989b6c00408dd6e5cf"`, undefined);
    await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_730de7831f17b647a4a0d5602ff"`, undefined);
    await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_0a0437d89bd29852d51db89b589"`, undefined);
    await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_aad9c3fcb70b081eac170c9f855"`, undefined);
    await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_bd374c8eb325f260166479c2518"`, undefined);
    await queryRunner.query(`ALTER TABLE "project" DROP CONSTRAINT "FK_b76640329fa79f0b0e9d031c35b"`, undefined);
    await queryRunner.query(`ALTER TABLE "payment_add_on" DROP CONSTRAINT "FK_cce8bed0f7eb60daae3c2031067"`, undefined);
    await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_e72528f4484a73df51e7578d54f"`, undefined);
    await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_b856cc54559328413b5652ab980"`, undefined);
    await queryRunner.query(`ALTER TABLE "customer_visit_history" DROP CONSTRAINT "FK_a63722084fb1d381526e4b66319"`, undefined);
    await queryRunner.query(`ALTER TABLE "customer_visit_history" DROP CONSTRAINT "FK_796a73e0119fa583f4fb6fb75c3"`, undefined);
    await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_01cd2b829e0263917bf570cb672"`, undefined);
    await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_bb8961abd76c46fcbd7644f6966"`, undefined);
    await queryRunner.query(`ALTER TABLE "consultation" DROP CONSTRAINT "FK_5fdef95bb1290b8daff57fa3b4b"`, undefined);
    await queryRunner.query(`ALTER TABLE "milestone" DROP CONSTRAINT "FK_edc28a2e0442554afe5eef2bdcb"`, undefined);
    await queryRunner.query(`ALTER TABLE "project_accessory" DROP CONSTRAINT "FK_e72d6667e0a330dfba21e0452f3"`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" DROP CONSTRAINT "FK_2c5dad24fda3550532497952ebc"`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" DROP CONSTRAINT "FK_1be8a3da9176bbd92660905c9de"`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" DROP CONSTRAINT "FK_ae5a68622fea0de6fdff500719e"`, undefined);
    await queryRunner.query(`ALTER TABLE "image_attachment" DROP CONSTRAINT "FK_79944b399d8cd03eb680c62b786"`, undefined);
    await queryRunner.query(`ALTER TABLE "site_visit_schedule" DROP CONSTRAINT "FK_10b08c17f53e1a2a7d8403e48b6"`, undefined);
    await queryRunner.query(`ALTER TABLE "estimate_item" DROP CONSTRAINT "FK_6d9aa5f11e0d5805802567d129a"`, undefined);
    await queryRunner.query(`ALTER TABLE "cost_estimate" DROP CONSTRAINT "FK_2239571281051540baf9b07e7e3"`, undefined);
    await queryRunner.query(`ALTER TABLE "project_procedure" DROP CONSTRAINT "FK_801d68af50498ef865562a2ea0a"`, undefined);
    await queryRunner.query(`ALTER TABLE "procedure_step" DROP CONSTRAINT "FK_35021ebabf1ce8152e4f2d3a986"`, undefined);
    await queryRunner.query(`ALTER TABLE "accessory_layout" DROP CONSTRAINT "FK_a94e33cc1557b3e696264b972a1"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_43a25f9db30db5c7bca3352738"`, undefined);
    await queryRunner.query(`DROP INDEX "IDX_88acbdbb95efe26f6a5fde1e96"`, undefined);
    await queryRunner.query(`DROP TABLE "user_ideas_idea"`, undefined);
    await queryRunner.query(`DROP TABLE "password_reset_link"`, undefined);
    await queryRunner.query(`DROP TABLE "portfolio"`, undefined);
    await queryRunner.query(`DROP TYPE "portfolio_materials_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "network_contractor_category"`, undefined);
    await queryRunner.query(`DROP TABLE "network_contractor"`, undefined);
    await queryRunner.query(`DROP TABLE "applicant"`, undefined);
    await queryRunner.query(`DROP TABLE "job"`, undefined);
    await queryRunner.query(`DROP TYPE "job_salarytype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "job_type_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "contact_us_message"`, undefined);
    await queryRunner.query(`DROP TABLE "chat"`, undefined);
    await queryRunner.query(`DROP TABLE "message"`, undefined);
    await queryRunner.query(`DROP TYPE "message_from_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "project"`, undefined);
    await queryRunner.query(`DROP TYPE "project_drainagetype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_soiltype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_propertygrade_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_machineaccess_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_preferredcolors_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_preferredpricepoint_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_materials_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_cleanuptype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_interestedinfinancing_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_timelinetype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_shapetype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_locationtype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_projecttype_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "refund"`, undefined);
    await queryRunner.query(`DROP TABLE "payment_add_on"`, undefined);
    await queryRunner.query(`DROP TABLE "customer_profile"`, undefined);
    await queryRunner.query(`DROP TABLE "user"`, undefined);
    await queryRunner.query(`DROP TYPE "user_invitationstatus_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "user_role_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "customer_visit_history"`, undefined);
    await queryRunner.query(`DROP TYPE "customer_visit_history_page_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "contractor_profile"`, undefined);
    await queryRunner.query(`DROP TABLE "event"`, undefined);
    await queryRunner.query(`DROP TABLE "consultation"`, undefined);
    await queryRunner.query(`DROP TABLE "patio_package"`, undefined);
    await queryRunner.query(`DROP TYPE "patio_package_additional_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "patio_package_packagetype_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "idea"`, undefined);
    await queryRunner.query(`DROP TYPE "idea_materialtypes_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "idea_projecttype_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "milestone"`, undefined);
    await queryRunner.query(`DROP TYPE "milestone_status_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "project_accessory"`, undefined);
    await queryRunner.query(`DROP TYPE "project_accessory_shape_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_accessory_locationtype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "project_accessory_materials_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "image_attachment"`, undefined);
    await queryRunner.query(`DROP TABLE "estimate"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_declinereasons_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_status_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_timelinetype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_costunit_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_shapetype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_locationtype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_materials_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_projecttype_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "site_visit_schedule"`, undefined);
    await queryRunner.query(`DROP TABLE "estimate_item"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_item_costunit_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_item_locationtype_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_item_materials_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "estimate_item_type_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "final_proposal"`, undefined);
    await queryRunner.query(`DROP TYPE "final_proposal_declinereasons_enum"`, undefined);
    await queryRunner.query(`DROP TYPE "final_proposal_status_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "cost_estimate"`, undefined);
    await queryRunner.query(`DROP TYPE "cost_estimate_type_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "project_procedure"`, undefined);
    await queryRunner.query(`DROP TYPE "project_procedure_type_enum"`, undefined);
    await queryRunner.query(`DROP TABLE "procedure_step"`, undefined);
    await queryRunner.query(`DROP TABLE "accessory_layout"`, undefined);
    await queryRunner.query(`DROP TYPE "accessory_layout_type_enum"`, undefined);
  }

}
